### ISSUE TITLE
Text unreadable in status bar

### ISSUE THREAD

**Issue by jonleopard** [tinted-theming/tinted-tmux#17]
Strangely enough, `base16-tmux` assigns a color that makes text unreadable in the status bar:

<img width="912" alt="Screenshot 2023-12-16 at 10 45 29" src="https://github.com/tinted-theming/base16-tmux/assets/2111234/cf128c52-f19b-4ae7-9acd-b3d4ebd92f31">

Here is what my status bar looks like without `base16-tmux` installed:
<img width="912" alt="Screenshot 2023-12-16 at 10 44 54" src="https://github.com/tinted-theming/base16-tmux/assets/2111234/017ed46e-6059-44bf-91d9-041b0c6be957">

#### Minimal config:
```
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# reload ~/.tmux.conf using PREFIX r
bind-key r source-file ~/.tmux.conf \; display-message "Reloaded!"

# Default terminal is 256 colors.
set -s default-terminal "screen-256color"

# Truecolor support
set -as terminal-features ',alacritty:RGB'

source-file $HOME/.config/tinted-theming/tmux.base16.conf
set -g allow-passthrough on

# Put the status bar up top
set -g status-position top

# -------------------------------------------------------------------
# TPM (Tmux Plugin Manager)
# -------------------------------------------------------------------


# First, install TPM if not present on system
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
#set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tinted-theming/base16-tmux'


set -g @tpm-clean 'P' # key binding to clean TPM plugins
run '~/.tmux/plugins/tpm/tpm'
```

I could modify my config to use something like this, but it seems odd that I would need to do that in order to make the text pop out.
```
set -g status-bg black
set -g status-fg white
```
<img width="912" alt="Screenshot 2023-12-16 at 10 58 01" src="https://github.com/tinted-theming/base16-tmux/assets/2111234/7dc1d30a-1f98-48f2-afd6-3a660e6d9656">

**Comment by JamyGolden** [comment]
Thanks for creating an issue, I'll have a look at this soon and get back to you.

**Comment by Andilutten** [comment]
I have the same issue

**Comment by JamyGolden** [comment]
I've merged a PR to fix the issue: https://github.com/tinted-theming/base16-tmux/pull/18. Can you please check to see if the problem is fixed for you?

Unrelated, but it's the reason I didn't notice this bug: You can have a more fancy looking statusbar if you have `export BASE16_TMUX_OPTION_STATUS="1"` set before tmux is launched.

![image](https://github.com/tinted-theming/base16-tmux/assets/602472/b6ebde14-51a9-4c5b-8f93-817a6644e539)

**Comment by jonleopard** [comment]
Looks great now! Thanks a bunch for looking into this.

Cheers mate!
