### ISSUE TITLE
[Bug report] Style change caused tabs to all be very bright

### ISSUE THREAD

**Issue by jonhoo** [tinted-theming/tinted-tmux#20]
## Describe the bug

The change in #14 had a pretty severe effect on gruvbox-dark-hard that I don't think was intentional, and (imo) looks quite a lot worse since it's so visually busy.

This is in an active window without the active option enabled (inactive window looks the same).

## Expected behavior

Style at 7dc46d5a0950ac7b647a1b4dcab0086a8d8650fb.

![2024-01-22-203915_2560x1440_scrot](https://github.com/tinted-theming/base16-tmux/assets/176295/31c8b346-f9e3-4291-a237-f95c9cafed29)

## Screenshots

Style at ff4ef2c5cd8023557ab997d259950047c5f17993 (the next commit), which built #14..

![2024-01-22-203941_2560x1440_scrot](https://github.com/tinted-theming/base16-tmux/assets/176295/fe23a748-10b8-4aab-96f0-da154a8e604e)

## **System**

**OS:** Arch Linux

**Tmux version:** tmux 3.3a

## Minimal configuration file

```
source-file colors/base16-gruvbox-dark-hard.conf
```

## Additional context

Confirmed as a bug by @JamyGolden in https://github.com/tinted-theming/base16-tmux/pull/14#issuecomment-1904722462.

**Comment by JamyGolden** [comment]
Thanks for creating the issue! I've fixed the bug, it's pretty straight forward but it would just be good for you to have a look over to make sure it's good. https://github.com/tinted-theming/base16-tmux/pull/21

Unrelated to this fix, but you can access two options that aren't available by default with the plugin, one of them is a better looking statusbar. Have the following 2 variables set before launching tmux:

```shell
export BASE16_TMUX_OPTION_ACTIVE="1"
export BASE16_TMUX_OPTION_STATUS="1"
```

Også, hei fra Oslo :)

**Comment by jonhoo** [comment]
The fix looks right to me!

I don't actually make use of blurred panes, so that first setting doesn't do much for me. The second one makes the bar way too prominent and visually verbose for my tastes :sweat_smile: 

On a somewhat related not, I think the README needs updating as it claims the variable is called `BASE16_TMUX_OPTION_STATUSBAR` (note the extra `BAR` at the end).

Og hei hei!

**Comment by JamyGolden** [comment]
Fair enough! and thanks for spotting that issue with the env var name :smile:
